services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules
    networks:
      - next_app_network
    user: node
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"

networks:
  next_app_network:
    name: sc-system-frontend_next_app_network
    driver: bridge

volumes:
  node_modules:
    name: next_app_node_modules
